# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-13 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField(default='Text')),
                ('timeStamp', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(default='1')),
            ],
        ),
    ]
